name: Prepare Release

on:
  workflow_dispatch:
  push:
    branches:
      - env/staging

jobs:
  prepare_release:
    name: Install and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v3
        with:
          script: |
            const releases = github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            console.log('releases', releases)
