name: Prepare Release

on:
  workflow_dispatch:
  push:
    branches:
      - env/staging

jobs:
  prepare_release:
    name: Draft Production Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./package.json
      - name: Check for previous releases with the same version
        uses: actions/github-script@v3
        env:
          PACKAGE_JSON_STRING: ${{steps.package.outputs.content}}
        with:
          script: |
            const package = JSON.parse(process.env.PACKAGE_JSON_STRING)
            // This does not include DRAFT releases (so the update bits in the next step still make sense)
            github.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: `v${package.version}`,
            }).then(response => {
              console.log('Found a previous release with this version number. Failing job.')
              console.log('response', response)
              throw new Error(`Version number "${package.version}" already used.`)
            }).catch(err => {
              if (err.status === 404) {
                console.log('✅ No published release with that version number found. Everything is good.')
              } else {
                // something else happened re-throw the error
                throw err;
              }
            })
      - name: Create or Update Release
        uses: actions/github-script@v3
        env:
          PACKAGE_JSON_STRING: ${{steps.package.outputs.content}}
        with:
          script: |
            const package = JSON.parse(process.env.PACKAGE_JSON_STRING)
            const response = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            const draft = response.data.find(rel => rel.draft)

            const name = `Release ${package.version} (${new Date().toISOString()})`
            if (draft) {
              console.log(`Draft release found: "${draft.name}"`)
              console.log(`Updating to: "${name}"...`)
              await github.repos.updateRelease({
                draft: true,
                name,
                owner: context.repo.owner,
                release_id: draft.id,
                repo: context.repo.repo,
                tag_name: `v${package.version}`,
                target_commitish: github.sha,
              })
            } else {
              console.log(`No draft release, Creating "${name}"...`)
              await github.repos.updateRelease({
                draft: true,
                name,
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: `v${package.version}`,
                target_commitish: github.sha,
              })
            }
